---
# tasks file for postfix
- name: >
    Debian | set_fact
      postfix_supported_os: True
  set_fact:
    postfix_supported_os: True

# https://wiki.debian.org/EtcMailName
- name: install /etc/mailname
  template: src=mailname.j2 dest=/etc/mailname owner=root group=root mode=0644

- name: install postfix
  apt: pkg=postfix state=installed update_cache=yes cache_valid_time=86400

# https://wiki.debian.org/PostfixAndSASL
- name: install libsasl2 packages needed for sasl-protected relaying
  apt: pkg=libsasl2-modules state=installed update_cache=yes cache_valid_time=86400
  apt: pkg=sasl2-bin state=installed update_cache=yes cache_valid_time=86400
